# Generated by Django 3.1.5 on 2022-11-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('RK', 'ROCK'), ('JZ', 'JAZZ'), ('CS', 'CLASSIC'), ('JP', 'J-POP')], default='RK', max_length=2),
        ),
    ]
